name: nightly_unit

on:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches: [ "nightly" ]
  pull_request:
    branches: [ "nightly" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        working-directory: ./civicfix_front_react_js
        run: yarn install --frozen-lockfile

      - name: Run tests
        working-directory: ./civicfix_front_react_js
        run: yarn test
